#!/bin/bash
set -e

# run the server
echo "==> Starting server..."
exec uvicorn --host "${BIND:-0.0.0.0}" --port "${PORT:-8000}" \
  --proxy-headers --forwarded-allow-ips "${FORWARDED_ALLOW_IPS:-*}" \
  src.main:app
